# Generated by Django 5.2.7 on 2025-11-16 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_siniestro', models.CharField(max_length=30, verbose_name='Número de siniestro')),
                ('nro_factura', models.CharField(blank=True, help_text='Formato: 000-0000000000', max_length=15, null=True, verbose_name='Número de factura')),
                ('fecha_factura', models.DateField(blank=True, null=True, verbose_name='Fecha de emisión de la factura')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
