# Generated by Django 5.2.7 on 2025-10-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abogados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('nro_abogado', models.IntegerField(unique=True)),
            ],
        ),
    ]
