# Generated by Django 5.2.7 on 2025-10-20 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0002_peritos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abogados',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='peritos',
            old_name='Apellido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='peritos',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
