# Generated by Django 5.2.7 on 2025-10-20 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0003_rename_nombre_abogados_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abogados',
            old_name='Apellido',
            new_name='apellido',
        ),
    ]
