# Generated by Django 5.2.7 on 2025-10-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0004_rename_apellido_abogados_apellido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisdicciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=3, unique=True)),
            ],
        ),
    ]
